
   Name           Domain             Range
   ----------------------------------------
   add            <.1,.2>            .3
   ----------------------------------------
   add            <.3,.4>            .5
   ----------------------------------------

 Directions -  <in,<in,in>> ~ out

 Wiring -  <.1,<.2,.4>> ~ .5

 Inputs -  .1 .2 .4
