
   Name           Domain             Range
   ----------------------------------------
   mult           <.1,.2>            .3
   add            <.1,.2>            .4
   ----------------------------------------

 Directions -  <in,in> ~ <out,out>

 Wiring -  <.1,.2> ~ <.3,.4>

 Inputs -  .1 .2
